apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: __IMAGE__
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-server
          containerPort: 3000
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: myapp
  type: NodePort
